name: Android CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]  # Tests aussi sur les PR vers develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 35.0.0 #34 -> 26

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
          echo "apiKey=${{ secrets.apiKey }}" >> local.properties

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Run lint checks
        run: ./gradlew lint || echo "Lint checks failed, see report for details"
        continue-on-error: true

      - name: Upload Lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports-${{ github.ref_name }}
          path: |
            app/build/reports/lint-results*
            app/build/intermediates/lint_intermediate_text_report/

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Run lint checks
        run: ./gradlew lint

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK (only on develop/main)
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.ref_name }}
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.ref_name }}
          path: |
            app/build/reports/
            app/build/test-results/